version: 2
sources:
  - name: datafeed_shared_schema
    database: "{{('dbt_db')}}"
    schema: staging_layer


    tables:
      - name: STG_CUSTOMERDATA
      - name: STG_PAYMENTS
      - name: STG_ORDER
      
      - name: STG_SUPPLIES_DATA
      
      - name: STG_PRODUCT_DATA

     

